import type { CdsAllergyRule, CdsDrugInteractionRule } from './cdsTypes'

export const SEED_DDI_RULES: CdsDrugInteractionRule[] = [
  {
    id: -1,
    drugA: 'warfarin',
    drugB: 'aspirin',
    severity: 'major',
    category: 'bleeding',
    messageEn: 'Increased bleeding risk (warfarin + aspirin)',
    messageAr: 'خطر نزيف متزايد (وارفارين + أسبرين)',
    actionEn: 'Avoid combination or monitor INR and signs of bleeding closely',
    actionAr: 'تجنب الجمع أو راقب INR وعلامات النزيف عن كثب',
    active: true,
  },
  {
    id: -2,
    drugA: 'warfarin',
    drugB: 'ibuprofen',
    severity: 'major',
    category: 'bleeding',
    messageEn: 'Increased bleeding risk (warfarin + NSAID)',
    messageAr: 'خطر نزيف متزايد (وارفارين + مضاد التهاب غير ستيروئيدي)',
    actionEn: 'Avoid NSAIDs with warfarin; consider acetaminophen if analgesia needed',
    actionAr: 'تجنب مضادات الالتهاب غير الستيروئيدية مع الوارفارين؛ فكّر في الباراسيتامول إذا لزم',
    active: true,
  },
  {
    id: -3,
    drugA: 'metformin',
    drugB: 'contrast',
    severity: 'moderate',
    category: 'other',
    messageEn: 'Hold metformin around iodinated contrast when applicable',
    messageAr: 'أوقف الميتفورمين حول صبغة اليود عندما ينطبق',
    actionEn: 'Hold metformin 48h before and after contrast; recheck renal function',
    actionAr: 'أوقف الميتفورمين 48 ساعة قبل وبعد الصبغة؛ أعد فحص وظائف الكلى',
    active: true,
  },
  {
    id: -4,
    drugA: 'simvastatin',
    drugB: 'clarithromycin',
    severity: 'major',
    category: 'myopathy',
    messageEn: 'Statin + clarithromycin — myopathy risk',
    messageAr: 'ستاتين + كلاريثروميسين — خطر اعتلال عضلي',
    actionEn: 'Avoid combination or temporarily hold statin during macrolide course',
    actionAr: 'تجنب الجمع أو أوقف الستاتين مؤقتًا أثناء دورة الماكروليد',
    active: true,
  },
  {
    id: -5,
    drugA: 'ssri',
    drugB: 'tramadol',
    severity: 'major',
    category: 'serotonin',
    messageEn: 'Serotonin syndrome risk (SSRI + tramadol)',
    messageAr: 'خطر متلازمة السيروتونين (SSRI + ترامادول)',
    actionEn: 'Avoid combination; monitor for agitation, hyperthermia, clonus',
    actionAr: 'تجنب الجمع؛ راقب الاضطراب والحمى والارتعاش',
    active: true,
  },
  {
    id: -6,
    drugA: 'fluoxetine',
    drugB: 'tramadol',
    severity: 'major',
    category: 'serotonin',
    messageEn: 'Serotonin syndrome risk (fluoxetine + tramadol)',
    messageAr: 'خطر متلازمة السيروتونين (فلوكسيتين + ترامادول)',
    actionEn: 'Avoid combination; consider alternative analgesic',
    actionAr: 'تجنب الجمع؛ فكّر في مسكن بديل',
    active: true,
  },
  {
    id: -7,
    drugA: 'ace inhibitor',
    drugB: 'potassium',
    severity: 'moderate',
    category: 'hyperkalemia',
    messageEn: 'Hyperkalemia risk (ACEI + potassium)',
    messageAr: 'خطر فرط بوتاسيوم الدم (مثبط ACE + بوتاسيوم)',
    actionEn: 'Monitor serum potassium; avoid routine potassium supplementation',
    actionAr: 'راقب البوتاسيوم في الدم؛ تجنب مكملات البوتاسيوم الروتينية',
    active: true,
  },
  {
    id: -8,
    drugA: 'digoxin',
    drugB: 'amiodarone',
    severity: 'major',
    category: 'toxicity',
    messageEn: 'Digoxin level may rise with amiodarone — monitor',
    messageAr: 'قد يرتفع مستوى الديجوكسين مع الأميودارون — راقب',
    actionEn: 'Reduce digoxin dose by ~50% and monitor levels',
    actionAr: 'قلل جرعة الديجوكسين بنحو 50% وراقب المستويات',
    active: true,
  },
  {
    id: -9,
    drugA: 'methotrexate',
    drugB: 'nsaid',
    severity: 'major',
    category: 'toxicity',
    messageEn: 'Methotrexate + NSAID — toxicity risk',
    messageAr: 'الميثوتريكسات + مضاد التهاب غير ستيروئيدي — خطر سمية',
    actionEn: 'Avoid NSAIDs with methotrexate; monitor CBC and renal function',
    actionAr: 'تجنب مضادات الالتهاب غير الستيروئيدية مع الميثوتريكسات؛ راقب صورة الدم والكلى',
    active: true,
  },
  {
    id: -10,
    drugA: 'methotrexate',
    drugB: 'ibuprofen',
    severity: 'major',
    category: 'toxicity',
    messageEn: 'Methotrexate + ibuprofen — toxicity risk',
    messageAr: 'الميثوتريكسات + إيبوبروفن — خطر سمية',
    actionEn: 'Avoid ibuprofen with methotrexate; use acetaminophen if needed',
    actionAr: 'تجنب الإيبوبروفن مع الميثوتريكسات؛ استخدم الباراسيتامول إذا لزم',
    active: true,
  },
  {
    id: -11,
    drugA: 'warfarin',
    drugB: 'naproxen',
    severity: 'major',
    category: 'bleeding',
    messageEn: 'Increased bleeding risk (warfarin + naproxen)',
    messageAr: 'خطر نزيف متزايد (وارفارين + نابروكسين)',
    actionEn: 'Avoid naproxen with warfarin; monitor INR if unavoidable',
    actionAr: 'تجنب نابروكسين مع الوارفارين؛ راقب INR إذا لم يُتجنّب',
    active: true,
  },
  {
    id: -12,
    drugA: 'lithium',
    drugB: 'ace inhibitor',
    severity: 'major',
    category: 'toxicity',
    messageEn: 'Lithium toxicity risk with ACE inhibitor',
    messageAr: 'خطر سمية الليثيوم مع مثبط ACE',
    actionEn: 'Monitor lithium levels closely; consider dose reduction',
    actionAr: 'راقب مستويات الليثيوم عن كثب؛ فكّر في تقليل الجرعة',
    active: true,
  },
  {
    id: -13,
    drugA: 'lithium',
    drugB: 'lisinopril',
    severity: 'major',
    category: 'toxicity',
    messageEn: 'Lithium toxicity risk with lisinopril',
    messageAr: 'خطر سمية الليثيوم مع ليسينوبريل',
    actionEn: 'Monitor lithium levels; adjust dose as needed',
    actionAr: 'راقب مستويات الليثيوم؛ عدّل الجرعة حسب الحاجة',
    active: true,
  },
  {
    id: -14,
    drugA: 'carbamazepine',
    drugB: 'erythromycin',
    severity: 'major',
    category: 'toxicity',
    messageEn: 'Carbamazepine level may rise with erythromycin',
    messageAr: 'قد يرتفع مستوى الكاربامازيبين مع الإريثروميسين',
    actionEn: 'Monitor carbamazepine levels and signs of toxicity',
    actionAr: 'راقب مستويات الكاربامازيبين وعلامات السمية',
    active: true,
  },
  {
    id: -15,
    drugA: 'phenytoin',
    drugB: 'fluconazole',
    severity: 'major',
    category: 'toxicity',
    messageEn: 'Phenytoin toxicity risk with fluconazole',
    messageAr: 'خطر سمية الفينيتوئين مع الفلوكونازول',
    actionEn: 'Monitor phenytoin levels; consider dose adjustment',
    actionAr: 'راقب مستويات الفينيتوئين؛ فكّر في تعديل الجرعة',
    active: true,
  },
  {
    id: -16,
    drugA: 'sertraline',
    drugB: 'linezolid',
    severity: 'major',
    category: 'serotonin',
    messageEn: 'Serotonin syndrome risk (sertraline + linezolid)',
    messageAr: 'خطر متلازمة السيروتونين (سرترالين + لينيزوليد)',
    actionEn: 'Avoid combination; linezolid has MAOI activity',
    actionAr: 'تجنب الجمع؛ لينيزوليد له نشاط MAOI',
    active: true,
  },
  {
    id: -17,
    drugA: 'atorvastatin',
    drugB: 'gemfibrozil',
    severity: 'major',
    category: 'myopathy',
    messageEn: 'Statin + gemfibrozil — myopathy and rhabdomyolysis risk',
    messageAr: 'ستاتين + جمفيبروزيل — خطر اعتلال عضلي وانحلال عضلي شديد',
    actionEn: 'Avoid combination or use lowest statin dose with monitoring',
    actionAr: 'تجنب الجمع أو استخدم أقل جرعة ستاتين مع المراقبة',
    active: true,
  },
  {
    id: -18,
    drugA: 'spironolactone',
    drugB: 'potassium',
    severity: 'moderate',
    category: 'hyperkalemia',
    messageEn: 'Hyperkalemia risk (spironolactone + potassium)',
    messageAr: 'خطر فرط بوتاسيوم الدم (سبيرونولاكتون + بوتاسيوم)',
    actionEn: 'Monitor serum potassium; avoid potassium supplements',
    actionAr: 'راقب البوتاسيوم في الدم؛ تجنب مكملات البوتاسيوم',
    active: true,
  },
]

export const SEED_ALLERGY_RULES: CdsAllergyRule[] = [
  {
    id: -101,
    allergyKey: 'penicillin',
    drugMatchers: ['amoxicillin', 'ampicillin', 'penicillin', 'augmentin'],
    severity: 'major',
    category: 'allergy_cross_reactivity',
    messageEn: 'Penicillin allergy — possible cross-reactivity with beta-lactam antibiotic',
    messageAr: 'حساسية البنسلين — احتمال تفاعل متقاطع مع مضاد حيوي بيتا-لاكتام',
    actionEn: 'Do not order without override reason; consider alternative antibiotic class',
    actionAr: 'لا تُصدر الطلب بدون سبب تجاوز؛ فكّر في فئة مضاد حيوي بديلة',
    active: true,
  },
  {
    id: -102,
    allergyKey: 'sulfa',
    drugMatchers: ['sulfamethoxazole', 'sulfadiazine', 'bactrim', 'co-trimoxazole'],
    severity: 'major',
    category: 'allergy_cross_reactivity',
    messageEn: 'Sulfa allergy — possible cross-reactivity with sulfonamide antibiotic',
    messageAr: 'حساسية السلفا — احتمال تفاعل متقاطع مع مضاد حيوي السلفوناميد',
    actionEn: 'Avoid sulfonamides; document override reason if clinically necessary',
    actionAr: 'تجنب مركبات السلفوناميد؛ وثّق سبب التجاوز إذا كان ضروريًا سريريًا',
    active: true,
  },
  {
    id: -103,
    allergyKey: 'aspirin',
    drugMatchers: ['aspirin', 'acetylsalicylic'],
    severity: 'major',
    category: 'allergy_cross_reactivity',
    messageEn: 'Aspirin allergy — salicylate exposure risk',
    messageAr: 'حساسية الأسبرين — خطر التعرض لمركبات الساليسيلات',
    actionEn: 'Avoid aspirin and related salicylates unless override documented',
    actionAr: 'تجنب الأسبرين ومركبات الساليسيلات المرتبطة ما لم يُوثّق التجاوز',
    active: true,
  },
  {
    id: -104,
    allergyKey: 'cephalosporin',
    drugMatchers: ['cefazolin', 'ceftriaxone', 'cephalexin', 'cefuroxime'],
    severity: 'major',
    category: 'allergy_cross_reactivity',
    messageEn: 'Cephalosporin allergy — avoid cephalosporin class agents',
    messageAr: 'حساسية السيفالوسبورين — تجنب عوامل فئة السيفالوسبورين',
    actionEn: 'Use alternative antibiotic; override reason required if ordering',
    actionAr: 'استخدم مضادًا حيويًا بديلًا؛ سبب التجاوز مطلوب عند الطلب',
    active: true,
  },
  {
    id: -105,
    allergyKey: 'codeine',
    drugMatchers: ['codeine', 'hydrocodone', 'tramadol'],
    severity: 'major',
    category: 'allergy_cross_reactivity',
    messageEn: 'Codeine/opioid allergy — possible cross-sensitivity',
    messageAr: 'حساسية الكوديين/الأفيون — احتمال حساسية متقاطعة',
    actionEn: 'Avoid related opioids; select non-cross-reactive analgesic',
    actionAr: 'تجنب الأفيونات المرتبطة؛ اختر مسكنًا غير متفاعل',
    active: true,
  },
  {
    id: -106,
    allergyKey: 'latex',
    drugMatchers: ['latex'],
    severity: 'moderate',
    category: 'allergy_cross_reactivity',
    messageEn: 'Latex allergy — verify medication packaging and excipients',
    messageAr: 'حساسية اللاتكس — تحقق من تغليف الدواء والمواد المضافة',
    actionEn: 'Confirm latex-free formulation before administration',
    actionAr: 'أكد تركيبة خالية من اللاتكس قبل الإعطاء',
    active: true,
  },
]
