-- AUTO-GENERATED by: npm run ops:bundle-sql
-- Do not edit by hand. Apply in Supabase SQL Editor (or psql) as one script.
-- Generated: 2026-08-09T08:42:05.514Z


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/schema.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Hospital Management System — Supabase Schema
-- Run this in Supabase SQL Editor
-- ============================================================

-- ── Users (extends auth.users) ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'patient' CHECK (role IN ('admin', 'doctor', 'nurse', 'patient')),
  avatar TEXT,
  linked_patient_id INTEGER REFERENCES public.patients(id) ON DELETE SET NULL,
  linked_doctor_id INTEGER REFERENCES public.doctors(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Auto-create profile on signup (role is ALWAYS patient — admins promote via dashboard)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    NEW.email,
    'patient'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── Patients ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.patients (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  phone TEXT NOT NULL,
  condition TEXT NOT NULL,
  last_visit TEXT NOT NULL,
  blood_type TEXT DEFAULT 'Unknown',
  allergies JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Doctors ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.doctors (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT NOT NULL,
  available BOOLEAN DEFAULT true,
  patients INTEGER DEFAULT 0,
  rating NUMERIC(2,1) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Appointments ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.appointments (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id INTEGER REFERENCES public.doctors(id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  doctor_name TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('confirmed', 'pending', 'cancelled', 'completed')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Clinical Visits (EHR) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.visits (
  id TEXT PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id INTEGER REFERENCES public.doctors(id) ON DELETE SET NULL,
  date TEXT NOT NULL,
  title TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Medications (EHR) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.medications (
  id TEXT PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  dosage TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Clinical Notes (EHR) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS public.notes (
  id TEXT PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Medical Files (EHR) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.medical_files (
  id TEXT PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  date TEXT NOT NULL,
  size INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Invoices (Billing) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.invoices (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  date TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'paid', 'partial')),
  paid_amount NUMERIC(10,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Medicines (Pharmacy) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS public.medicines (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  stock INTEGER DEFAULT 0,
  unit_price NUMERIC(10,2) DEFAULT 0,
  expiry_date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Pharmacy Orders ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pharmacy_orders (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  medicine_id INTEGER REFERENCES public.medicines(id) ON DELETE CASCADE,
  medicine_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'dispensed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Lab Tests ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lab_tests (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER REFERENCES public.patients(id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  test_name TEXT NOT NULL,
  category TEXT NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ordered' CHECK (status IN ('ordered', 'in-progress', 'completed', 'cancelled')),
  result TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── Audit Log ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_log (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_name TEXT,
  action TEXT NOT NULL,
  table_name TEXT NOT NULL,
  record_id TEXT,
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
-- Policies created after current_user_role() helper below

-- ── updated_at trigger function ───────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── Add updated_at columns ────────────────────────────────
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.doctors ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.visits ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.medications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.medical_files ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.medicines ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.pharmacy_orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.lab_tests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- ── Create updated_at triggers ────────────────────────────
DO $$
DECLARE t TEXT;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'profiles', 'patients', 'doctors', 'appointments', 'visits',
    'medications', 'notes', 'medical_files', 'invoices',
    'medicines', 'pharmacy_orders', 'lab_tests'
  ])
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS set_updated_at ON public.%I', t);
    EXECUTE format('CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()', t);
  END LOOP;
END $$;

-- ── Row Level Security ────────────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_tests ENABLE ROW LEVEL SECURITY;

-- ── Helper functions for RLS ──────────────────────────────
CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS TEXT AS $$
  SELECT COALESCE(
    (SELECT role FROM public.profiles WHERE id = auth.uid()),
    'patient'
  );
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.current_user_patient_id()
RETURNS INTEGER AS $$
  SELECT linked_patient_id FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.current_user_doctor_id()
RETURNS INTEGER AS $$
  SELECT linked_doctor_id FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

-- ── Audit log policies (after helpers) ────────────────────
CREATE POLICY "Admin read audit_log" ON public.audit_log FOR SELECT TO authenticated
  USING (public.current_user_role() = 'admin');
CREATE POLICY "Authenticated insert own audit_log" ON public.audit_log FOR INSERT TO authenticated
  WITH CHECK (user_id IS NULL OR user_id = auth.uid());

-- ── Profiles: self or admin ───────────────────────────────
CREATE POLICY "Profiles self read" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Profiles admin read all" ON public.profiles FOR SELECT TO authenticated USING (public.current_user_role() = 'admin');
CREATE POLICY "Profiles self update" ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id); -- role changes blocked by prevent_role_self_escalation trigger
CREATE POLICY "Profiles admin update all" ON public.profiles FOR UPDATE TO authenticated USING (public.current_user_role() = 'admin');

-- Prevent non-admins from changing their own role
CREATE OR REPLACE FUNCTION public.prevent_role_self_escalation()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.role IS DISTINCT FROM OLD.role AND public.current_user_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only admin can change roles';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS prevent_role_self_escalation ON public.profiles;
CREATE TRIGGER prevent_role_self_escalation
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.prevent_role_self_escalation();

-- ── Patients: staff see all, patient sees own record ──────
CREATE POLICY "Patients staff read" ON public.patients FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Patients self read" ON public.patients FOR SELECT TO authenticated
  USING (id = public.current_user_patient_id());
CREATE POLICY "Patients staff insert" ON public.patients FOR INSERT TO authenticated
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Patients staff update" ON public.patients FOR UPDATE TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Patients admin delete" ON public.patients FOR DELETE TO authenticated
  USING (public.current_user_role() = 'admin');

-- ── Doctors: staff read all, patient reads assigned doctor ─
CREATE POLICY "Doctors staff read" ON public.doctors FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Doctors patient read" ON public.doctors FOR SELECT TO authenticated
  USING (public.current_user_role() = 'patient');
CREATE POLICY "Doctors admin write" ON public.doctors FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin');

-- ── Appointments: staff see all, patient sees own ─────────
CREATE POLICY "Appointments staff read" ON public.appointments FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Appointments patient read" ON public.appointments FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Appointments staff write" ON public.appointments FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

-- ── Visits: staff see all, patient sees own ───────────────
CREATE POLICY "Visits staff read" ON public.visits FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Visits patient read" ON public.visits FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Visits doctor write" ON public.visits FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor'));

-- ── Medications: staff see all, patient sees own ──────────
CREATE POLICY "Medications staff read" ON public.medications FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Medications patient read" ON public.medications FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Medications doctor write" ON public.medications FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor'));

-- ── Notes: staff see all, patient sees own ────────────────
CREATE POLICY "Notes staff read" ON public.notes FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Notes patient read" ON public.notes FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Notes staff write" ON public.notes FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

-- ── Medical Files: staff see all, patient sees own ────────
CREATE POLICY "Files staff read" ON public.medical_files FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Files patient read" ON public.medical_files FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Files staff write" ON public.medical_files FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

-- ── Invoices: admin/billing see all, patient sees own ─────
CREATE POLICY "Invoices admin read" ON public.invoices FOR SELECT TO authenticated
  USING (public.current_user_role() = 'admin');
CREATE POLICY "Invoices patient read" ON public.invoices FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Invoices admin write" ON public.invoices FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin');

-- ── Medicines: staff see all, patient read ────────────────
CREATE POLICY "Medicines staff read" ON public.medicines FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Medicines patient read" ON public.medicines FOR SELECT TO authenticated
  USING (public.current_user_role() = 'patient');
CREATE POLICY "Medicines admin nurse write" ON public.medicines FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'nurse'));

-- ── Pharmacy Orders: staff see all, patient sees own ──────
CREATE POLICY "Pharmacy orders staff read" ON public.pharmacy_orders FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Pharmacy orders patient read" ON public.pharmacy_orders FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Pharmacy orders admin nurse write" ON public.pharmacy_orders FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'nurse'));

-- ── Lab Tests: staff see all, patient sees own ────────────
CREATE POLICY "Lab tests staff read" ON public.lab_tests FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Lab tests patient read" ON public.lab_tests FOR SELECT TO authenticated
  USING (patient_id = public.current_user_patient_id());
CREATE POLICY "Lab tests staff write" ON public.lab_tests FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

-- ── Indexes ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON public.appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor ON public.appointments(doctor_id);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON public.appointments(date);
CREATE INDEX IF NOT EXISTS idx_visits_patient ON public.visits(patient_id);
CREATE INDEX IF NOT EXISTS idx_medications_patient ON public.medications(patient_id);
CREATE INDEX IF NOT EXISTS idx_notes_patient ON public.notes(patient_id);
CREATE INDEX IF NOT EXISTS idx_files_patient ON public.medical_files(patient_id);
CREATE INDEX IF NOT EXISTS idx_invoices_patient ON public.invoices(patient_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_orders_patient ON public.pharmacy_orders(patient_id);
CREATE INDEX IF NOT EXISTS idx_lab_tests_patient ON public.lab_tests(patient_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user ON public.audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_table ON public.audit_log(table_name);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON public.audit_log(created_at);

-- ── Storage Bucket for Medical Files (PRIVATE) ────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('medical-files', 'medical-files', false)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

-- Staff can read all objects; patients only their linked patient folder
CREATE POLICY "Staff read medical-files bucket" ON storage.objects
  FOR SELECT TO authenticated USING (
    bucket_id = 'medical-files' AND
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
  );

CREATE POLICY "Patient read own medical-files bucket" ON storage.objects
  FOR SELECT TO authenticated USING (
    bucket_id = 'medical-files' AND
    public.current_user_role() = 'patient' AND
    (storage.foldername(name))[1] = public.current_user_patient_id()::text
  );

CREATE POLICY "Staff write medical-files bucket" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (
    bucket_id = 'medical-files' AND
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('admin', 'doctor', 'nurse'))
  );

CREATE POLICY "Staff delete medical-files bucket" ON storage.objects
  FOR DELETE TO authenticated USING (
    bucket_id = 'medical-files' AND
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('admin', 'doctor', 'nurse'))
  );

-- Phase A: consent + retention — see supabase/phase-a-compliance.sql (apply on existing projects too)
-- Phase C1: payments + claims — see supabase/phase-c-payments.sql
-- Phase C2: remittances — see supabase/phase-c2-interop.sql

-- END supabase/schema.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/security-hardening.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Security hardening migration (run on existing Supabase projects)
-- Safe to re-run: drops/replaces policies and functions.
-- ============================================================

-- 1) Signup cannot self-assign admin/doctor/nurse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    NEW.email,
    'patient'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2) Block non-admin role changes
CREATE OR REPLACE FUNCTION public.prevent_role_self_escalation()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.role IS DISTINCT FROM OLD.role AND public.current_user_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only admin can change roles';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS prevent_role_self_escalation ON public.profiles;
CREATE TRIGGER prevent_role_self_escalation
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.prevent_role_self_escalation();

-- 3) Audit log: admin read; insert only as self
DROP POLICY IF EXISTS "Authenticated read audit_log" ON public.audit_log;
DROP POLICY IF EXISTS "Staff write audit_log" ON public.audit_log;
DROP POLICY IF EXISTS "Admin read audit_log" ON public.audit_log;
DROP POLICY IF EXISTS "Authenticated insert own audit_log" ON public.audit_log;
CREATE POLICY "Admin read audit_log" ON public.audit_log FOR SELECT TO authenticated
  USING (public.current_user_role() = 'admin');
CREATE POLICY "Authenticated insert own audit_log" ON public.audit_log FOR INSERT TO authenticated
  WITH CHECK (user_id IS NULL OR user_id = auth.uid());

-- 4) Patients: split write; delete = admin only
DROP POLICY IF EXISTS "Patients staff write" ON public.patients;
DROP POLICY IF EXISTS "Patients staff insert" ON public.patients;
DROP POLICY IF EXISTS "Patients staff update" ON public.patients;
DROP POLICY IF EXISTS "Patients admin delete" ON public.patients;
CREATE POLICY "Patients staff insert" ON public.patients FOR INSERT TO authenticated
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Patients staff update" ON public.patients FOR UPDATE TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Patients admin delete" ON public.patients FOR DELETE TO authenticated
  USING (public.current_user_role() = 'admin');

-- 5) Private medical-files bucket + path-scoped patient read
UPDATE storage.buckets SET public = false WHERE id = 'medical-files';

DROP POLICY IF EXISTS "Authenticated read medical-files bucket" ON storage.objects;
DROP POLICY IF EXISTS "Staff read medical-files bucket" ON storage.objects;
DROP POLICY IF EXISTS "Patient read own medical-files bucket" ON storage.objects;
DROP POLICY IF EXISTS "Staff write medical-files bucket" ON storage.objects;
DROP POLICY IF EXISTS "Staff delete medical-files bucket" ON storage.objects;

CREATE POLICY "Staff read medical-files bucket" ON storage.objects
  FOR SELECT TO authenticated USING (
    bucket_id = 'medical-files' AND
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
  );

CREATE POLICY "Patient read own medical-files bucket" ON storage.objects
  FOR SELECT TO authenticated USING (
    bucket_id = 'medical-files' AND
    public.current_user_role() = 'patient' AND
    (storage.foldername(name))[1] = public.current_user_patient_id()::text
  );

CREATE POLICY "Staff write medical-files bucket" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (
    bucket_id = 'medical-files' AND
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('admin', 'doctor', 'nurse'))
  );

CREATE POLICY "Staff delete medical-files bucket" ON storage.objects
  FOR DELETE TO authenticated USING (
    bucket_id = 'medical-files' AND
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('admin', 'doctor', 'nurse'))
  );

-- END supabase/security-hardening.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-a-compliance.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase A compliance (run on Supabase SQL editor after schema)
-- Consent records (server-side) + retention purge helpers
-- Safe to re-run.
-- ============================================================

-- ── Consent records ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.consent_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  consent_type TEXT NOT NULL
    CHECK (consent_type IN ('data_processing', 'marketing', 'analytics', 'third_party_share')),
  granted BOOLEAN NOT NULL,
  version TEXT NOT NULL DEFAULT '1.0.0',
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, consent_type)
);

CREATE INDEX IF NOT EXISTS idx_consent_records_user ON public.consent_records(user_id);

ALTER TABLE public.consent_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Consent select own or admin" ON public.consent_records;
DROP POLICY IF EXISTS "Consent insert own" ON public.consent_records;
DROP POLICY IF EXISTS "Consent update own" ON public.consent_records;

CREATE POLICY "Consent select own or admin" ON public.consent_records
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.current_user_role() = 'admin');

CREATE POLICY "Consent insert own" ON public.consent_records
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Consent update own" ON public.consent_records
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ── Retention purge audit ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.retention_purge_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name TEXT NOT NULL,
  rows_deleted INTEGER NOT NULL DEFAULT 0,
  cutoff TIMESTAMPTZ NOT NULL,
  ran_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ran_by TEXT
);

ALTER TABLE public.retention_purge_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin read retention_purge_log" ON public.retention_purge_log;
CREATE POLICY "Admin read retention_purge_log" ON public.retention_purge_log
  FOR SELECT TO authenticated
  USING (public.current_user_role() = 'admin');

-- ── Purge function (SECURITY DEFINER — call via Edge / cron only) ─
-- Clinical tables (visits, notes, meds, lab, invoices, audit) keep 7y;
-- this job only removes operational rows past policy windows.
CREATE OR REPLACE FUNCTION public.purge_expired_records(p_ran_by TEXT DEFAULT 'system')
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_appt INTEGER := 0;
  v_pharm INTEGER := 0;
  v_cutoff_appt TIMESTAMPTZ := now() - INTERVAL '2 years';
  v_cutoff_pharm TIMESTAMPTZ := now() - INTERVAL '3 years';
BEGIN
  -- Completed/cancelled appointments older than 2 years
  DELETE FROM public.appointments
  WHERE status IN ('completed', 'cancelled')
    AND COALESCE(updated_at, created_at) < v_cutoff_appt;
  GET DIAGNOSTICS v_appt = ROW_COUNT;

  INSERT INTO public.retention_purge_log (table_name, rows_deleted, cutoff, ran_by)
  VALUES ('appointments', v_appt, v_cutoff_appt, p_ran_by);

  -- Pharmacy orders older than 3 years
  DELETE FROM public.pharmacy_orders
  WHERE COALESCE(updated_at, created_at) < v_cutoff_pharm;
  GET DIAGNOSTICS v_pharm = ROW_COUNT;

  INSERT INTO public.retention_purge_log (table_name, rows_deleted, cutoff, ran_by)
  VALUES ('pharmacy_orders', v_pharm, v_cutoff_pharm, p_ran_by);

  INSERT INTO public.audit_log (user_id, user_name, action, table_name, record_id, details)
  VALUES (
    NULL,
    p_ran_by,
    'retention_purge',
    'system',
    NULL,
    jsonb_build_object(
      'appointments', v_appt,
      'pharmacy_orders', v_pharm,
      'ran_by', p_ran_by
    )
  );

  RETURN jsonb_build_object(
    'ok', true,
    'appointments_deleted', v_appt,
    'pharmacy_orders_deleted', v_pharm,
    'cutoff_appointments', v_cutoff_appt,
    'cutoff_pharmacy_orders', v_cutoff_pharm
  );
END;
$$;

REVOKE ALL ON FUNCTION public.purge_expired_records(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.purge_expired_records(TEXT) TO service_role;

-- END supabase/phase-a-compliance.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-c-payments.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase C1 — payments, claims, invoice currency
-- Safe to re-run. Apply after schema + security-hardening.
-- ============================================================

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'USD';

-- ── Payments ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGSERIAL PRIMARY KEY,
  invoice_id INTEGER NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  patient_id INTEGER NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  currency TEXT NOT NULL DEFAULT 'USD',
  provider TEXT NOT NULL CHECK (provider IN ('stripe', 'mock')),
  provider_ref TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_provider_ref
  ON public.payments(provider, provider_ref)
  WHERE provider_ref IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payments_invoice ON public.payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_patient ON public.payments(patient_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments(status);

DROP TRIGGER IF EXISTS set_updated_at_payments ON public.payments;
CREATE TRIGGER set_updated_at_payments
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Payments admin read" ON public.payments;
DROP POLICY IF EXISTS "Payments patient read" ON public.payments;
DROP POLICY IF EXISTS "Payments admin write" ON public.payments;

CREATE POLICY "Payments admin read" ON public.payments
  FOR SELECT TO authenticated
  USING (public.current_user_role() = 'admin');

CREATE POLICY "Payments patient read" ON public.payments
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() = 'patient'
    AND patient_id = public.current_user_patient_id()
  );

CREATE POLICY "Payments admin write" ON public.payments
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- Inserts from Edge (service role) bypass RLS; patients never insert directly.

-- ── Claims (simplified international stub) ────────────────
CREATE TABLE IF NOT EXISTS public.claims (
  id BIGSERIAL PRIMARY KEY,
  invoice_id INTEGER NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  patient_id INTEGER NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  payer_name TEXT NOT NULL DEFAULT 'Self-Pay',
  icd10_codes TEXT[] NOT NULL DEFAULT '{}',
  cpt_codes TEXT[] NOT NULL DEFAULT '{}',
  total NUMERIC(10,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'submitted', 'accepted', 'rejected', 'paid')),
  external_ref TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_claims_invoice ON public.claims(invoice_id);
CREATE INDEX IF NOT EXISTS idx_claims_patient ON public.claims(patient_id);
CREATE INDEX IF NOT EXISTS idx_claims_status ON public.claims(status);

DROP TRIGGER IF EXISTS set_updated_at_claims ON public.claims;
CREATE TRIGGER set_updated_at_claims
  BEFORE UPDATE ON public.claims
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Claims admin all" ON public.claims;
CREATE POLICY "Claims admin all" ON public.claims
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- END supabase/phase-c-payments.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-c2-interop.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase C2 — remittances (ERA stub) + claim paid linkage
-- Safe to re-run. Apply after phase-c-payments.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS public.remittances (
  id BIGSERIAL PRIMARY KEY,
  claim_id BIGINT NOT NULL REFERENCES public.claims(id) ON DELETE CASCADE,
  payer_name TEXT NOT NULL,
  amount_paid NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  amount_adjusted NUMERIC(10,2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL DEFAULT 'posted'
    CHECK (status IN ('posted', 'denied', 'partial')),
  remittance_ref TEXT,
  notes TEXT,
  posted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_remittances_claim ON public.remittances(claim_id);

ALTER TABLE public.remittances ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Remittances admin all" ON public.remittances;
CREATE POLICY "Remittances admin all" ON public.remittances
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- END supabase/phase-c2-interop.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-c3-remaining.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase C3 — Remaining interop: patient messages + ERA audit note
-- Safe to re-run. Apply after phase-c2-interop.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS public.patient_messages (
  id BIGSERIAL PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  subject TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  sender_role TEXT NOT NULL CHECK (sender_role IN ('admin', 'doctor', 'nurse', 'patient')),
  sender_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_patient_messages_patient ON public.patient_messages(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_messages_created ON public.patient_messages(created_at DESC);

ALTER TABLE public.patient_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Messages staff all" ON public.patient_messages;
CREATE POLICY "Messages staff all" ON public.patient_messages
  FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'))
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

DROP POLICY IF EXISTS "Messages patient own" ON public.patient_messages;
CREATE POLICY "Messages patient own" ON public.patient_messages
  FOR ALL TO authenticated
  USING (
    public.current_user_role() = 'patient'
    AND patient_id = public.current_user_patient_id()
  )
  WITH CHECK (
    public.current_user_role() = 'patient'
    AND patient_id = public.current_user_patient_id()
    AND sender_role = 'patient'
  );

-- Optional: store last ERA import raw on remittances.notes already covers audit.
COMMENT ON TABLE public.patient_messages IS 'Phase C3 patient–staff messaging';

-- END supabase/phase-c3-remaining.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-b1-adt.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase B1 — ADT: wards, beds, admissions
-- Safe to re-run. Apply after Phase C SQL if present.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.wards (
  id SERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  floor TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.beds (
  id SERIAL PRIMARY KEY,
  ward_id INTEGER NOT NULL REFERENCES public.wards(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'available'
    CHECK (status IN ('available', 'occupied', 'cleaning', 'blocked')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (ward_id, label)
);

CREATE INDEX IF NOT EXISTS idx_beds_ward ON public.beds(ward_id);
CREATE INDEX IF NOT EXISTS idx_beds_status ON public.beds(status);

CREATE TABLE IF NOT EXISTS public.admissions (
  id BIGSERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES public.patients(id) ON DELETE RESTRICT,
  patient_name TEXT NOT NULL,
  bed_id INTEGER NOT NULL REFERENCES public.beds(id) ON DELETE RESTRICT,
  ward_id INTEGER NOT NULL REFERENCES public.wards(id) ON DELETE RESTRICT,
  attending_doctor_id INTEGER REFERENCES public.doctors(id) ON DELETE SET NULL,
  attending_doctor_name TEXT,
  status TEXT NOT NULL DEFAULT 'admitted'
    CHECK (status IN ('admitted', 'discharged')),
  admit_reason TEXT,
  admitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  discharged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admissions_patient ON public.admissions(patient_id);
CREATE INDEX IF NOT EXISTS idx_admissions_bed ON public.admissions(bed_id);
CREATE INDEX IF NOT EXISTS idx_admissions_status ON public.admissions(status);

-- At most one active admission per patient
CREATE UNIQUE INDEX IF NOT EXISTS idx_admissions_one_active_patient
  ON public.admissions(patient_id)
  WHERE status = 'admitted';

-- At most one active admission per bed
CREATE UNIQUE INDEX IF NOT EXISTS idx_admissions_one_active_bed
  ON public.admissions(bed_id)
  WHERE status = 'admitted';

DROP TRIGGER IF EXISTS set_updated_at_admissions ON public.admissions;
CREATE TRIGGER set_updated_at_admissions
  BEFORE UPDATE ON public.admissions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.wards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Wards staff read" ON public.wards;
DROP POLICY IF EXISTS "Wards admin write" ON public.wards;
CREATE POLICY "Wards staff read" ON public.wards
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Wards admin write" ON public.wards
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

DROP POLICY IF EXISTS "Beds staff read" ON public.beds;
DROP POLICY IF EXISTS "Beds staff write" ON public.beds;
CREATE POLICY "Beds staff read" ON public.beds
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Beds staff write" ON public.beds
  FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'))
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

DROP POLICY IF EXISTS "Admissions staff read" ON public.admissions;
DROP POLICY IF EXISTS "Admissions staff write" ON public.admissions;
CREATE POLICY "Admissions staff read" ON public.admissions
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Admissions staff write" ON public.admissions
  FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'))
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

-- Seed demo wards/beds (idempotent by code)
INSERT INTO public.wards (code, name, floor)
VALUES
  ('MED-A', 'Medical Ward A', '2'),
  ('SUR-B', 'Surgical Ward B', '3'),
  ('ICU', 'Intensive Care', '4')
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.beds (ward_id, label, status)
SELECT w.id, b.label, 'available'
FROM public.wards w
CROSS JOIN (VALUES ('1'), ('2'), ('3'), ('4')) AS b(label)
WHERE w.code IN ('MED-A', 'SUR-B', 'ICU')
  AND NOT EXISTS (
    SELECT 1 FROM public.beds x WHERE x.ward_id = w.id AND x.label = b.label
  );

-- END supabase/phase-b1-adt.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-b2-clinical.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase B2 — Vitals + Problem List
-- Safe to re-run. Apply after phase-b1-adt.sql (recommended).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.vital_signs (
  id BIGSERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  admission_id BIGINT REFERENCES public.admissions(id) ON DELETE SET NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  recorded_by TEXT,
  temperature_c NUMERIC(4,1),
  heart_rate INTEGER,
  respiratory_rate INTEGER,
  systolic_bp INTEGER,
  diastolic_bp INTEGER,
  spo2 INTEGER,
  weight_kg NUMERIC(5,1),
  height_cm NUMERIC(5,1),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vital_signs_patient ON public.vital_signs(patient_id);
CREATE INDEX IF NOT EXISTS idx_vital_signs_recorded ON public.vital_signs(recorded_at DESC);

CREATE TABLE IF NOT EXISTS public.problems (
  id BIGSERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  code TEXT,
  display TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'resolved', 'inactive')),
  severity TEXT CHECK (severity IS NULL OR severity IN ('mild', 'moderate', 'severe')),
  onset_date DATE,
  resolved_date DATE,
  notes TEXT,
  recorded_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_problems_patient ON public.problems(patient_id);
CREATE INDEX IF NOT EXISTS idx_problems_status ON public.problems(status);

DROP TRIGGER IF EXISTS set_updated_at_problems ON public.problems;
CREATE TRIGGER set_updated_at_problems
  BEFORE UPDATE ON public.problems
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.vital_signs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.problems ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Vitals staff read" ON public.vital_signs;
DROP POLICY IF EXISTS "Vitals patient read" ON public.vital_signs;
DROP POLICY IF EXISTS "Vitals staff write" ON public.vital_signs;
CREATE POLICY "Vitals staff read" ON public.vital_signs
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Vitals patient read" ON public.vital_signs
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() = 'patient'
    AND patient_id = public.current_user_patient_id()
  );
CREATE POLICY "Vitals staff write" ON public.vital_signs
  FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'))
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

DROP POLICY IF EXISTS "Problems staff read" ON public.problems;
DROP POLICY IF EXISTS "Problems patient read" ON public.problems;
DROP POLICY IF EXISTS "Problems staff write" ON public.problems;
CREATE POLICY "Problems staff read" ON public.problems
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Problems patient read" ON public.problems
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() = 'patient'
    AND patient_id = public.current_user_patient_id()
  );
CREATE POLICY "Problems staff write" ON public.problems
  FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'))
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

-- Demo seed (idempotent: only if empty for patient 103)
INSERT INTO public.vital_signs (
  patient_id, recorded_at, recorded_by,
  temperature_c, heart_rate, respiratory_rate, systolic_bp, diastolic_bp, spo2, notes
)
SELECT 103, now() - interval '2 hours', 'Nurse Demo',
  37.2, 88, 18, 128, 82, 97, 'Admission baseline'
WHERE EXISTS (SELECT 1 FROM public.patients WHERE id = 103)
  AND NOT EXISTS (SELECT 1 FROM public.vital_signs WHERE patient_id = 103);

INSERT INTO public.problems (patient_id, code, display, status, severity, onset_date, recorded_by)
SELECT 103, 'E11.9', 'Type 2 diabetes mellitus', 'active', 'moderate', CURRENT_DATE - 365, 'Dr Demo'
WHERE EXISTS (SELECT 1 FROM public.patients WHERE id = 103)
  AND NOT EXISTS (SELECT 1 FROM public.problems WHERE patient_id = 103 AND code = 'E11.9');

-- END supabase/phase-b2-clinical.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-b3-cpoe.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase B3 — CPOE (clinical orders)
-- Safe to re-run. Apply after phase-b2-clinical.sql (recommended).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.clinical_orders (
  id BIGSERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  order_type TEXT NOT NULL
    CHECK (order_type IN ('lab', 'pharmacy', 'imaging', 'nursing', 'other')),
  status TEXT NOT NULL DEFAULT 'ordered'
    CHECK (status IN ('draft', 'ordered', 'in-progress', 'completed', 'cancelled')),
  priority TEXT NOT NULL DEFAULT 'routine'
    CHECK (priority IN ('routine', 'urgent', 'stat')),
  description TEXT NOT NULL,
  code TEXT,
  medicine_id INTEGER REFERENCES public.medicines(id) ON DELETE SET NULL,
  quantity INTEGER,
  ordered_by TEXT,
  ordered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes TEXT,
  allergy_alert TEXT,
  linked_lab_test_id INTEGER REFERENCES public.lab_tests(id) ON DELETE SET NULL,
  linked_pharmacy_order_id INTEGER REFERENCES public.pharmacy_orders(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clinical_orders_patient ON public.clinical_orders(patient_id);
CREATE INDEX IF NOT EXISTS idx_clinical_orders_status ON public.clinical_orders(status);
CREATE INDEX IF NOT EXISTS idx_clinical_orders_type ON public.clinical_orders(order_type);
CREATE INDEX IF NOT EXISTS idx_clinical_orders_ordered ON public.clinical_orders(ordered_at DESC);

DROP TRIGGER IF EXISTS set_updated_at_clinical_orders ON public.clinical_orders;
CREATE TRIGGER set_updated_at_clinical_orders
  BEFORE UPDATE ON public.clinical_orders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.clinical_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Orders staff read" ON public.clinical_orders;
DROP POLICY IF EXISTS "Orders patient read" ON public.clinical_orders;
DROP POLICY IF EXISTS "Orders staff write" ON public.clinical_orders;
CREATE POLICY "Orders staff read" ON public.clinical_orders
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "Orders patient read" ON public.clinical_orders
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() = 'patient'
    AND patient_id = public.current_user_patient_id()
  );
CREATE POLICY "Orders staff write" ON public.clinical_orders
  FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'))
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

-- Demo seed
INSERT INTO public.clinical_orders (
  patient_id, patient_name, order_type, status, priority, description, code, ordered_by, ordered_at
)
SELECT 103, 'Khalid Al-Rashid', 'lab', 'ordered', 'routine', 'HbA1c', '4548-4', 'Dr Demo', now() - interval '1 day'
WHERE EXISTS (SELECT 1 FROM public.patients WHERE id = 103)
  AND NOT EXISTS (
    SELECT 1 FROM public.clinical_orders WHERE patient_id = 103 AND description = 'HbA1c' AND order_type = 'lab'
  );

-- END supabase/phase-b3-cpoe.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-b3b-cds-rules.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase B3b — CDS rules (drug–drug + allergy) + order columns
-- Safe to re-run. Apply after phase-b3-cpoe.sql.
-- Seed mirrors src/lib/cdsSeed.ts (18 DDI + 6 allergy rows).
-- ============================================================

-- ── Drug–drug interaction rules ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.cds_drug_interactions (
  id BIGSERIAL PRIMARY KEY,
  drug_a TEXT NOT NULL,
  drug_b TEXT NOT NULL,
  severity TEXT NOT NULL
    CHECK (severity IN ('major', 'moderate')),
  category TEXT NOT NULL,
  message_en TEXT NOT NULL,
  message_ar TEXT NOT NULL,
  action_en TEXT NOT NULL,
  action_ar TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cds_ddi_pair_unique
  ON public.cds_drug_interactions (lower(drug_a), lower(drug_b));

CREATE INDEX IF NOT EXISTS idx_cds_ddi_active ON public.cds_drug_interactions(active);

DROP TRIGGER IF EXISTS set_updated_at_cds_drug_interactions ON public.cds_drug_interactions;
CREATE TRIGGER set_updated_at_cds_drug_interactions
  BEFORE UPDATE ON public.cds_drug_interactions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.cds_drug_interactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "CDS DDI clinical read" ON public.cds_drug_interactions;
DROP POLICY IF EXISTS "CDS DDI admin write" ON public.cds_drug_interactions;
CREATE POLICY "CDS DDI clinical read" ON public.cds_drug_interactions
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND (active = true OR public.current_user_role() = 'admin')
  );
CREATE POLICY "CDS DDI admin write" ON public.cds_drug_interactions
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- ── Allergy cross-reactivity rules ──────────────────────────
CREATE TABLE IF NOT EXISTS public.cds_allergy_rules (
  id BIGSERIAL PRIMARY KEY,
  allergy_key TEXT NOT NULL,
  drug_matchers TEXT[] NOT NULL,
  severity TEXT NOT NULL
    CHECK (severity IN ('major', 'moderate')),
  category TEXT NOT NULL,
  message_en TEXT NOT NULL,
  message_ar TEXT NOT NULL,
  action_en TEXT NOT NULL,
  action_ar TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cds_allergy_key_unique
  ON public.cds_allergy_rules (lower(allergy_key));

CREATE INDEX IF NOT EXISTS idx_cds_allergy_active ON public.cds_allergy_rules(active);

DROP TRIGGER IF EXISTS set_updated_at_cds_allergy_rules ON public.cds_allergy_rules;
CREATE TRIGGER set_updated_at_cds_allergy_rules
  BEFORE UPDATE ON public.cds_allergy_rules
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.cds_allergy_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "CDS allergy clinical read" ON public.cds_allergy_rules;
DROP POLICY IF EXISTS "CDS allergy admin write" ON public.cds_allergy_rules;
CREATE POLICY "CDS allergy clinical read" ON public.cds_allergy_rules
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND (active = true OR public.current_user_role() = 'admin')
  );
CREATE POLICY "CDS allergy admin write" ON public.cds_allergy_rules
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- ── clinical_orders CDS persistence columns ─────────────────
ALTER TABLE public.clinical_orders
  ADD COLUMN IF NOT EXISTS cds_alerts_json JSONB,
  ADD COLUMN IF NOT EXISTS cds_override_reason TEXT,
  ADD COLUMN IF NOT EXISTS cds_acknowledged_by TEXT,
  ADD COLUMN IF NOT EXISTS cds_acknowledged_at TIMESTAMPTZ;

-- ── Seed: drug–drug interactions (idempotent) ───────────────
INSERT INTO public.cds_drug_interactions (
  drug_a, drug_b, severity, category, message_en, message_ar, action_en, action_ar, active
)
SELECT v.drug_a, v.drug_b, v.severity, v.category, v.message_en, v.message_ar, v.action_en, v.action_ar, true
FROM (VALUES
  ('warfarin', 'aspirin', 'major', 'bleeding',
    'Increased bleeding risk (warfarin + aspirin)',
    'خطر نزيف متزايد (وارفارين + أسبرين)',
    'Avoid combination or monitor INR and signs of bleeding closely',
    'تجنب الجمع أو راقب INR وعلامات النزيف عن كثب'),
  ('warfarin', 'ibuprofen', 'major', 'bleeding',
    'Increased bleeding risk (warfarin + NSAID)',
    'خطر نزيف متزايد (وارفارين + مضاد التهاب غير ستيروئيدي)',
    'Avoid NSAIDs with warfarin; consider acetaminophen if analgesia needed',
    'تجنب مضادات الالتهاب غير الستيروئيدية مع الوارفارين؛ فكّر في الباراسيتامول إذا لزم'),
  ('metformin', 'contrast', 'moderate', 'other',
    'Hold metformin around iodinated contrast when applicable',
    'أوقف الميتفورمين حول صبغة اليود عندما ينطبق',
    'Hold metformin 48h before and after contrast; recheck renal function',
    'أوقف الميتفورمين 48 ساعة قبل وبعد الصبغة؛ أعد فحص وظائف الكلى'),
  ('simvastatin', 'clarithromycin', 'major', 'myopathy',
    'Statin + clarithromycin — myopathy risk',
    'ستاتين + كلاريثروميسين — خطر اعتلال عضلي',
    'Avoid combination or temporarily hold statin during macrolide course',
    'تجنب الجمع أو أوقف الستاتين مؤقتًا أثناء دورة الماكروليد'),
  ('ssri', 'tramadol', 'major', 'serotonin',
    'Serotonin syndrome risk (SSRI + tramadol)',
    'خطر متلازمة السيروتونين (SSRI + ترامادول)',
    'Avoid combination; monitor for agitation, hyperthermia, clonus',
    'تجنب الجمع؛ راقب الاضطراب والحمى والارتعاش'),
  ('fluoxetine', 'tramadol', 'major', 'serotonin',
    'Serotonin syndrome risk (fluoxetine + tramadol)',
    'خطر متلازمة السيروتونين (فلوكسيتين + ترامادول)',
    'Avoid combination; consider alternative analgesic',
    'تجنب الجمع؛ فكّر في مسكن بديل'),
  ('ace inhibitor', 'potassium', 'moderate', 'hyperkalemia',
    'Hyperkalemia risk (ACEI + potassium)',
    'خطر فرط بوتاسيوم الدم (مثبط ACE + بوتاسيوم)',
    'Monitor serum potassium; avoid routine potassium supplementation',
    'راقب البوتاسيوم في الدم؛ تجنب مكملات البوتاسيوم الروتينية'),
  ('digoxin', 'amiodarone', 'major', 'toxicity',
    'Digoxin level may rise with amiodarone — monitor',
    'قد يرتفع مستوى الديجوكسين مع الأميودارون — راقب',
    'Reduce digoxin dose by ~50% and monitor levels',
    'قلل جرعة الديجوكسين بنحو 50% وراقب المستويات'),
  ('methotrexate', 'nsaid', 'major', 'toxicity',
    'Methotrexate + NSAID — toxicity risk',
    'الميثوتريكسات + مضاد التهاب غير ستيروئيدي — خطر سمية',
    'Avoid NSAIDs with methotrexate; monitor CBC and renal function',
    'تجنب مضادات الالتهاب غير الستيروئيدية مع الميثوتريكسات؛ راقب صورة الدم والكلى'),
  ('methotrexate', 'ibuprofen', 'major', 'toxicity',
    'Methotrexate + ibuprofen — toxicity risk',
    'الميثوتريكسات + إيبوبروفن — خطر سمية',
    'Avoid ibuprofen with methotrexate; use acetaminophen if needed',
    'تجنب الإيبوبروفن مع الميثوتريكسات؛ استخدم الباراسيتامول إذا لزم'),
  ('warfarin', 'naproxen', 'major', 'bleeding',
    'Increased bleeding risk (warfarin + naproxen)',
    'خطر نزيف متزايد (وارفارين + نابروكسين)',
    'Avoid naproxen with warfarin; monitor INR if unavoidable',
    'تجنب نابروكسين مع الوارفارين؛ راقب INR إذا لم يُتجنّب'),
  ('lithium', 'ace inhibitor', 'major', 'toxicity',
    'Lithium toxicity risk with ACE inhibitor',
    'خطر سمية الليثيوم مع مثبط ACE',
    'Monitor lithium levels closely; consider dose reduction',
    'راقب مستويات الليثيوم عن كثب؛ فكّر في تقليل الجرعة'),
  ('lithium', 'lisinopril', 'major', 'toxicity',
    'Lithium toxicity risk with lisinopril',
    'خطر سمية الليثيوم مع ليسينوبريل',
    'Monitor lithium levels; adjust dose as needed',
    'راقب مستويات الليثيوم؛ عدّل الجرعة حسب الحاجة'),
  ('carbamazepine', 'erythromycin', 'major', 'toxicity',
    'Carbamazepine level may rise with erythromycin',
    'قد يرتفع مستوى الكاربامازيبين مع الإريثروميسين',
    'Monitor carbamazepine levels and signs of toxicity',
    'راقب مستويات الكاربامازيبين وعلامات السمية'),
  ('phenytoin', 'fluconazole', 'major', 'toxicity',
    'Phenytoin toxicity risk with fluconazole',
    'خطر سمية الفينيتوئين مع الفلوكونازول',
    'Monitor phenytoin levels; consider dose adjustment',
    'راقب مستويات الفينيتوئين؛ فكّر في تعديل الجرعة'),
  ('sertraline', 'linezolid', 'major', 'serotonin',
    'Serotonin syndrome risk (sertraline + linezolid)',
    'خطر متلازمة السيروتونين (سرترالين + لينيزوليد)',
    'Avoid combination; linezolid has MAOI activity',
    'تجنب الجمع؛ لينيزوليد له نشاط MAOI'),
  ('atorvastatin', 'gemfibrozil', 'major', 'myopathy',
    'Statin + gemfibrozil — myopathy and rhabdomyolysis risk',
    'ستاتين + جمفيبروزيل — خطر اعتلال عضلي وانحلال عضلي شديد',
    'Avoid combination or use lowest statin dose with monitoring',
    'تجنب الجمع أو استخدم أقل جرعة ستاتين مع المراقبة'),
  ('spironolactone', 'potassium', 'moderate', 'hyperkalemia',
    'Hyperkalemia risk (spironolactone + potassium)',
    'خطر فرط بوتاسيوم الدم (سبيرونولاكتون + بوتاسيوم)',
    'Monitor serum potassium; avoid potassium supplements',
    'راقب البوتاسيوم في الدم؛ تجنب مكملات البوتاسيوم')
) AS v(drug_a, drug_b, severity, category, message_en, message_ar, action_en, action_ar)
WHERE NOT EXISTS (
  SELECT 1 FROM public.cds_drug_interactions d
  WHERE lower(d.drug_a) = lower(v.drug_a) AND lower(d.drug_b) = lower(v.drug_b)
);

-- ── Seed: allergy rules (idempotent) ──────────────────────────
INSERT INTO public.cds_allergy_rules (
  allergy_key, drug_matchers, severity, category, message_en, message_ar, action_en, action_ar, active
)
SELECT v.allergy_key, v.drug_matchers, v.severity, v.category, v.message_en, v.message_ar, v.action_en, v.action_ar, true
FROM (VALUES
  ('penicillin', ARRAY['amoxicillin', 'ampicillin', 'penicillin', 'augmentin']::TEXT[], 'major', 'allergy_cross_reactivity',
    'Penicillin allergy — possible cross-reactivity with beta-lactam antibiotic',
    'حساسية البنسلين — احتمال تفاعل متقاطع مع مضاد حيوي بيتا-لاكتام',
    'Do not order without override reason; consider alternative antibiotic class',
    'لا تُصدر الطلب بدون سبب تجاوز؛ فكّر في فئة مضاد حيوي بديلة'),
  ('sulfa', ARRAY['sulfamethoxazole', 'sulfadiazine', 'bactrim', 'co-trimoxazole']::TEXT[], 'major', 'allergy_cross_reactivity',
    'Sulfa allergy — possible cross-reactivity with sulfonamide antibiotic',
    'حساسية السلفا — احتمال تفاعل متقاطع مع مضاد حيوي السلفوناميد',
    'Avoid sulfonamides; document override reason if clinically necessary',
    'تجنب مركبات السلفوناميد؛ وثّق سبب التجاوز إذا كان ضروريًا سريريًا'),
  ('aspirin', ARRAY['aspirin', 'acetylsalicylic']::TEXT[], 'major', 'allergy_cross_reactivity',
    'Aspirin allergy — salicylate exposure risk',
    'حساسية الأسبرين — خطر التعرض لمركبات الساليسيلات',
    'Avoid aspirin and related salicylates unless override documented',
    'تجنب الأسبرين ومركبات الساليسيلات المرتبطة ما لم يُوثّق التجاوز'),
  ('cephalosporin', ARRAY['cefazolin', 'ceftriaxone', 'cephalexin', 'cefuroxime']::TEXT[], 'major', 'allergy_cross_reactivity',
    'Cephalosporin allergy — avoid cephalosporin class agents',
    'حساسية السيفالوسبورين — تجنب عوامل فئة السيفالوسبورين',
    'Use alternative antibiotic; override reason required if ordering',
    'استخدم مضادًا حيويًا بديلًا؛ سبب التجاوز مطلوب عند الطلب'),
  ('codeine', ARRAY['codeine', 'hydrocodone', 'tramadol']::TEXT[], 'major', 'allergy_cross_reactivity',
    'Codeine/opioid allergy — possible cross-sensitivity',
    'حساسية الكوديين/الأفيون — احتمال حساسية متقاطعة',
    'Avoid related opioids; select non-cross-reactive analgesic',
    'تجنب الأفيونات المرتبطة؛ اختر مسكنًا غير متفاعل'),
  ('latex', ARRAY['latex']::TEXT[], 'moderate', 'allergy_cross_reactivity',
    'Latex allergy — verify medication packaging and excipients',
    'حساسية اللاتكس — تحقق من تغليف الدواء والمواد المضافة',
    'Confirm latex-free formulation before administration',
    'أكد تركيبة خالية من اللاتكس قبل الإعطاء')
) AS v(allergy_key, drug_matchers, severity, category, message_en, message_ar, action_en, action_ar)
WHERE NOT EXISTS (
  SELECT 1 FROM public.cds_allergy_rules a
  WHERE lower(a.allergy_key) = lower(v.allergy_key)
);

-- END supabase/phase-b3b-cds-rules.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-b4-emar.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase B4 — eMAR (medication administration record)
-- Safe to re-run. Apply after phase-b3-cpoe.sql.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.medication_administrations (
  id BIGSERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  medicine_name TEXT NOT NULL,
  dose TEXT NOT NULL,
  route TEXT DEFAULT 'oral',
  scheduled_at TIMESTAMPTZ NOT NULL,
  administered_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'given', 'held', 'refused', 'missed')),
  administered_by TEXT,
  notes TEXT,
  clinical_order_id BIGINT REFERENCES public.clinical_orders(id) ON DELETE SET NULL,
  pharmacy_order_id INTEGER REFERENCES public.pharmacy_orders(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mar_patient ON public.medication_administrations(patient_id);
CREATE INDEX IF NOT EXISTS idx_mar_status ON public.medication_administrations(status);
CREATE INDEX IF NOT EXISTS idx_mar_scheduled ON public.medication_administrations(scheduled_at);

DROP TRIGGER IF EXISTS set_updated_at_mar ON public.medication_administrations;
CREATE TRIGGER set_updated_at_mar
  BEFORE UPDATE ON public.medication_administrations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.medication_administrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "MAR staff read" ON public.medication_administrations;
DROP POLICY IF EXISTS "MAR patient read" ON public.medication_administrations;
DROP POLICY IF EXISTS "MAR staff write" ON public.medication_administrations;
CREATE POLICY "MAR staff read" ON public.medication_administrations
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'));
CREATE POLICY "MAR patient read" ON public.medication_administrations
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() = 'patient'
    AND patient_id = public.current_user_patient_id()
  );
CREATE POLICY "MAR staff write" ON public.medication_administrations
  FOR ALL TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse'))
  WITH CHECK (public.current_user_role() IN ('admin', 'doctor', 'nurse'));

INSERT INTO public.medication_administrations (
  patient_id, patient_name, medicine_name, dose, route, scheduled_at, status
)
SELECT 103, 'Khalid Al-Rashid', 'Metformin 500mg', '500 mg', 'oral',
  now() + interval '1 hour', 'scheduled'
WHERE EXISTS (SELECT 1 FROM public.patients WHERE id = 103)
  AND NOT EXISTS (
    SELECT 1 FROM public.medication_administrations
    WHERE patient_id = 103 AND medicine_name = 'Metformin 500mg' AND status = 'scheduled'
  );

-- END supabase/phase-b4-emar.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-d-enterprise.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase D — Enterprise: facilities, memberships, SCIM audit
-- Safe to re-run. Apply after phase-c3-remaining.sql (or after B4).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.facilities (
  id BIGSERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  city TEXT,
  timezone TEXT NOT NULL DEFAULT 'Asia/Riyadh',
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.facility_memberships (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  facility_id BIGINT NOT NULL REFERENCES public.facilities(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'staff'
    CHECK (role IN ('admin', 'doctor', 'nurse', 'staff')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, facility_id)
);

CREATE INDEX IF NOT EXISTS idx_facility_memberships_user ON public.facility_memberships(user_id);
CREATE INDEX IF NOT EXISTS idx_facility_memberships_facility ON public.facility_memberships(facility_id);

-- Scope patients to a facility (nullable = legacy / all-facility admin view)
ALTER TABLE public.patients
  ADD COLUMN IF NOT EXISTS facility_id BIGINT REFERENCES public.facilities(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_patients_facility ON public.patients(facility_id);

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS active_facility_id BIGINT REFERENCES public.facilities(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS external_idp_sub TEXT,
  ADD COLUMN IF NOT EXISTS scim_external_id TEXT;

CREATE TABLE IF NOT EXISTS public.compliance_attestations (
  id BIGSERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'in_progress', 'done', 'na')),
  notes TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facility_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_attestations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Facilities staff read" ON public.facilities;
CREATE POLICY "Facilities staff read" ON public.facilities
  FOR SELECT TO authenticated
  USING (public.current_user_role() IN ('admin', 'doctor', 'nurse', 'patient'));

DROP POLICY IF EXISTS "Facilities admin write" ON public.facilities;
CREATE POLICY "Facilities admin write" ON public.facilities
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

DROP POLICY IF EXISTS "Memberships admin all" ON public.facility_memberships;
CREATE POLICY "Memberships admin all" ON public.facility_memberships
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

DROP POLICY IF EXISTS "Memberships self read" ON public.facility_memberships;
CREATE POLICY "Memberships self read" ON public.facility_memberships
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.current_user_role() = 'admin');

DROP POLICY IF EXISTS "Compliance admin all" ON public.compliance_attestations;
CREATE POLICY "Compliance admin all" ON public.compliance_attestations
  FOR ALL TO authenticated
  USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- Seed demo facilities
INSERT INTO public.facilities (code, name, city, timezone)
VALUES
  ('MAIN', 'City Hospital — Main Campus', 'Riyadh', 'Asia/Riyadh'),
  ('NORTH', 'City Hospital — North Clinic', 'Riyadh', 'Asia/Riyadh')
ON CONFLICT (code) DO NOTHING;

-- Default compliance checklist
INSERT INTO public.compliance_attestations (key, label, status) VALUES
  ('baa_signed', 'Business Associate Agreement (BAA) signed with vendors', 'pending'),
  ('encryption_at_rest', 'PHI encryption at rest (KMS / Edge secrets)', 'in_progress'),
  ('encryption_in_transit', 'TLS everywhere (app, API, storage)', 'done'),
  ('access_control', 'RBAC + MFA for privileged roles', 'done'),
  ('audit_logging', 'Immutable audit log for PHI access', 'done'),
  ('retention_policy', 'Data retention & purge schedule active', 'in_progress'),
  ('breach_plan', 'Incident / breach response playbook', 'pending'),
  ('workforce_training', 'Workforce HIPAA/privacy training', 'pending'),
  ('dlp_exports', 'DLP redaction on exports / downloads', 'in_progress'),
  ('sso_scim', 'SSO + SCIM lifecycle for workforce accounts', 'pending')
ON CONFLICT (key) DO NOTHING;

COMMENT ON TABLE public.facilities IS 'Phase D multi-facility tenancy';
COMMENT ON TABLE public.compliance_attestations IS 'Phase D HIPAA/BAA checklist stubs';

-- END supabase/phase-d-enterprise.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-d2-facility-rls.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase D2 — Facility-scoped RLS helpers (automatable hardening)
-- Apply after phase-d-enterprise.sql
-- ============================================================

CREATE OR REPLACE FUNCTION public.current_user_facility_ids()
RETURNS SETOF BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT facility_id
  FROM public.facility_memberships
  WHERE user_id = auth.uid()
  UNION
  SELECT active_facility_id
  FROM public.profiles
  WHERE id = auth.uid() AND active_facility_id IS NOT NULL;
$$;

CREATE OR REPLACE FUNCTION public.user_can_access_facility(p_facility_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.current_user_role() = 'admin'
    OR p_facility_id IS NULL
    OR p_facility_id IN (SELECT public.current_user_facility_ids());
$$;

-- Tighten patients: staff still read all if no memberships; when memberships exist, scope by facility
DROP POLICY IF EXISTS "Patients staff read" ON public.patients;
CREATE POLICY "Patients staff read" ON public.patients
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND (
      public.current_user_role() = 'admin'
      OR NOT EXISTS (SELECT 1 FROM public.facility_memberships WHERE user_id = auth.uid())
      OR facility_id IS NULL
      OR public.user_can_access_facility(facility_id)
    )
  );

DROP POLICY IF EXISTS "Patients staff insert" ON public.patients;
CREATE POLICY "Patients staff insert" ON public.patients
  FOR INSERT TO authenticated
  WITH CHECK (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND public.user_can_access_facility(facility_id)
  );

DROP POLICY IF EXISTS "Patients staff update" ON public.patients;
CREATE POLICY "Patients staff update" ON public.patients
  FOR UPDATE TO authenticated
  USING (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND public.user_can_access_facility(facility_id)
  )
  WITH CHECK (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND public.user_can_access_facility(facility_id)
  );

COMMENT ON FUNCTION public.current_user_facility_ids() IS 'Phase D2: facilities the current user may access';

-- END supabase/phase-d2-facility-rls.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-d3-facility-clinical-rls.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase D3 — Facility scope on clinical rows via patient.facility_id
-- Apply after phase-d2-facility-rls.sql
-- ============================================================

CREATE OR REPLACE FUNCTION public.patient_facility_accessible(p_patient_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.current_user_role() = 'admin'
    OR NOT EXISTS (SELECT 1 FROM public.facility_memberships WHERE user_id = auth.uid())
    OR EXISTS (
      SELECT 1 FROM public.patients p
      WHERE p.id = p_patient_id
        AND (
          p.facility_id IS NULL
          OR public.user_can_access_facility(p.facility_id)
        )
    );
$$;

-- Appointments
DROP POLICY IF EXISTS "Appointments staff read" ON public.appointments;
CREATE POLICY "Appointments staff read" ON public.appointments
  FOR SELECT TO authenticated
  USING (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND public.patient_facility_accessible(patient_id)
  );

DROP POLICY IF EXISTS "Appointments staff write" ON public.appointments;
CREATE POLICY "Appointments staff write" ON public.appointments
  FOR ALL TO authenticated
  USING (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND public.patient_facility_accessible(patient_id)
  )
  WITH CHECK (
    public.current_user_role() IN ('admin', 'doctor', 'nurse')
    AND public.patient_facility_accessible(patient_id)
  );

-- Lab tests (if table exists from earlier phases)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'lab_tests') THEN
    EXECUTE 'DROP POLICY IF EXISTS "Lab staff read" ON public.lab_tests';
    EXECUTE $p$
      CREATE POLICY "Lab staff read" ON public.lab_tests
        FOR SELECT TO authenticated
        USING (
          public.current_user_role() IN ('admin', 'doctor', 'nurse')
          AND public.patient_facility_accessible(patient_id)
        )
    $p$;
    EXECUTE 'DROP POLICY IF EXISTS "Lab staff write" ON public.lab_tests';
    EXECUTE $p$
      CREATE POLICY "Lab staff write" ON public.lab_tests
        FOR ALL TO authenticated
        USING (
          public.current_user_role() IN ('admin', 'doctor', 'nurse')
          AND public.patient_facility_accessible(patient_id)
        )
        WITH CHECK (
          public.current_user_role() IN ('admin', 'doctor', 'nurse')
          AND public.patient_facility_accessible(patient_id)
        )
    $p$;
  END IF;
END $$;

-- Invoices
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'invoices') THEN
    EXECUTE 'DROP POLICY IF EXISTS "Invoices staff read" ON public.invoices';
    EXECUTE $p$
      CREATE POLICY "Invoices staff read" ON public.invoices
        FOR SELECT TO authenticated
        USING (
          public.current_user_role() IN ('admin', 'doctor', 'nurse')
          AND public.patient_facility_accessible(patient_id)
        )
    $p$;
  END IF;
END $$;

-- Clinical orders
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'clinical_orders') THEN
    EXECUTE 'DROP POLICY IF EXISTS "Orders staff read" ON public.clinical_orders';
    EXECUTE 'DROP POLICY IF EXISTS "Clinical orders staff read" ON public.clinical_orders';
    EXECUTE $p$
      CREATE POLICY "Clinical orders staff facility read" ON public.clinical_orders
        FOR SELECT TO authenticated
        USING (
          public.current_user_role() IN ('admin', 'doctor', 'nurse')
          AND public.patient_facility_accessible(patient_id)
        )
    $p$;
  END IF;
END $$;

COMMENT ON FUNCTION public.patient_facility_accessible(BIGINT) IS 'Phase D3: row access via patient facility membership';

-- END supabase/phase-d3-facility-clinical-rls.sql


-- ══════════════════════════════════════════════════════════════
-- BEGIN supabase/phase-a-cron.sql
-- ══════════════════════════════════════════════════════════════

-- ============================================================
-- Phase A add-on — schedule retention purge via pg_cron
-- Requires: pg_cron enabled (Supabase Pro+) + phase-a-compliance.sql
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

DO $$
BEGIN
  -- Remove previous schedule if present
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'dynex360-retention-purge') THEN
    PERFORM cron.unschedule('dynex360-retention-purge');
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'purge_expired_records'
  ) THEN
    PERFORM cron.schedule(
      'dynex360-retention-purge',
      '15 2 * * *',
      $cron$SELECT public.purge_expired_records('pg_cron');$cron$
    );
    RAISE NOTICE 'Scheduled dynex360-retention-purge daily 02:15 UTC';
  ELSE
    RAISE NOTICE 'purge_expired_records() missing — apply phase-a-compliance.sql first';
  END IF;
EXCEPTION
  WHEN undefined_table THEN
    RAISE NOTICE 'cron.job unavailable — enable pg_cron (Database → Extensions) on Pro+';
  WHEN OTHERS THEN
    RAISE NOTICE 'pg_cron schedule skipped: %', SQLERRM;
END $$;

-- END supabase/phase-a-cron.sql

